title: Shuangjie Zhang
position: Postdoctoral Fellow
affiliation: University of Texas at Austin
email: shuangjie.zhang@austin.utexas.edu
baseurl: ""
keywords: minimal academic
avatar: ./assets/img/Shuangjie-Zhang.jpg
google_analytics: G-BFJ64HGEP2
favicon: ./assets/img/1.jpeg
favicon_dark: ./assets/img/1.jpeg
description: Shuangjie Zhang is a Postdoctoral Fellow in Statistics and Data Sciences at UT Austin, developing Bayesian methods for high-dimensional and dependent data, including factor models, graphical models, and density regression.
url: https://shuang-jie.github.io
remote_theme: yaoyao-liu/minimal-light
github_link: https://github.com/shuang-jie
# google_scholar: https://scholar.google.com/citations?user=YOUR_ID
linkedin: https://www.linkedin.com/in/shuangjie-zhang-9544a8146
nav_items:
  - title: Home
    url: /
    icon: fas fa-home
  - title: Research
    url: /research.html
    icon: fas fa-flask
  - title: Teaching
    url: /teaching.html
    icon: fas fa-chalkboard-teacher
  - title: Misc
    url: /misc.html
    icon: fas fa-star
